<%@ Page Title="" Language="C#" MasterPageFile="~/Master.Master" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="Bootstrap.WebForm1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-sm-12 bg-danger">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sodales finibus nunc, ultrices dignissim ligula laoreet eu. Sed ornare semper dui nec efficitur. Morbi vitae pretium metus. Ut eget quam iaculis, venenatis est a, elementum leo. Nullam quam nisl, auctor vitae odio condimentum, bibendum rutrum est. Suspendisse vitae eleifend est. Nulla aliquet eget quam et pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nibh lacus, aliquet non urna in, ornare scelerisque urna. Ut malesuada felis sapien, convallis congue nisi dapibus mollis. Quisque dapibus finibus turpis, a molestie nulla ultricies ut. Aliquam posuere quam in quam sodales blandit.</div>
            <div class="col-md-6 col-sm-12 bg-info">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sodales finibus nunc, ultrices dignissim ligula laoreet eu. Sed ornare semper dui nec efficitur. Morbi vitae pretium metus. Ut eget quam iaculis, venenatis est a, elementum leo. Nullam quam nisl, auctor vitae odio condimentum, bibendum rutrum est. Suspendisse vitae eleifend est. Nulla aliquet eget quam et pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nibh lacus, aliquet non urna in, ornare scelerisque urna. Ut malesuada felis sapien, convallis congue nisi dapibus mollis. Quisque dapibus finibus turpis, a molestie nulla ultricies ut. Aliquam posuere quam in quam sodales blandit.</div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-12 bg-light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sodales finibus nunc, ultrices dignissim ligula laoreet eu. Sed ornare semper dui nec efficitur. Morbi vitae pretium metus. Ut eget quam iaculis, venenatis est a, elementum leo. Nullam quam nisl, auctor vitae odio condimentum, bibendum rutrum est. Suspendisse vitae eleifend est. Nulla aliquet eget quam et pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nibh lacus, aliquet non urna in, ornare scelerisque urna. Ut malesuada felis sapien, convallis congue nisi dapibus mollis. Quisque dapibus finibus turpis, a molestie nulla ultricies ut. Aliquam posuere quam in quam sodales blandit.</div>
            <div class="col-md-6 col-sm-12 bg-success">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sodales finibus nunc, ultrices dignissim ligula laoreet eu. Sed ornare semper dui nec efficitur. Morbi vitae pretium metus. Ut eget quam iaculis, venenatis est a, elementum leo. Nullam quam nisl, auctor vitae odio condimentum, bibendum rutrum est. Suspendisse vitae eleifend est. Nulla aliquet eget quam et pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nibh lacus, aliquet non urna in, ornare scelerisque urna. Ut malesuada felis sapien, convallis congue nisi dapibus mollis. Quisque dapibus finibus turpis, a molestie nulla ultricies ut. Aliquam posuere quam in quam sodales blandit.</div>
        </div>
    </div>
</asp:Content>
